### ISSUE TITLE
New swish api endpoints

### ISSUE THREAD

**Issue by robertpiira** [squish-platform/swish-payments#1]
Hi!

According to the [latest docs](https://developer.getswish.se/content/uploads/2017/04/MerchantsAPI_Getswish_180504.pdf) 
there are some changes to SWISH_ENDPOINT and SWISH_PAYMENT_IP. 

On top of this I'm curious (and probably looking for help) on how you created '1231181189.p12'.

So, I've been trying out the project and it works great against the old Test api with your p12 file. But I'm having no luck on any attempts against the new endpoint / creation of the p12 file according to the new docs.

Any kind of tips/updates towards the new docs would be great. thanks.

**Comment by carlbarrdahl** [comment]
Hey,
Thanks for the heads up! :+1: 

Did a fix so you can know instance the library by specifying `endpoint` and `serverIP`. Should make it more robust to unforseen changes from Swish.

```js
const swish = new Swish({
  endpoint: "https://mss.swicpc.bankgirot.se/swish-cpcapi/api/v1",
  serverIP: "213.132.115.94:443",
  cert: {
    pfx: fs.readFileSync(__dirname + "/ssl/1231181189.p12"),
    passphrase: "swish"
  }
})
```

As for the certificate, you can download it from the left pane here:
https://developer.getswish.se/merchants-test-con/1-introduction/

Let me know if you have any further issues or questions.
